/* DDL - DATA DEFINITION LANGUAGE */

/* TABELA É UM CONJUNTO DE DADOS */

/* ALTER TABLE*/
ALTER TABLE TABELA
CHANGE COLUNA1 COLUNA2 INT NOT NULL;

/* MODIFY*/

/*ALTERANDO O TIPO*/
ALTER TABLE TABELA
MODIFY COLUNA VARCHAR(50) NOT NULL;

/*ADICIONANDO COLUNAS*/

/* ADICIONANDO COLUNA NO ORDEM ESPECIFICA (AFTER -> DEPOIS DE UMA DETERMINADA COLUNA) */
ALTER TABLE TABELA
ADD COLUMN COLUNA FLOAT(10,2) NOT NULL
AFTER COLUNA;

/* ADICIONANDO COLUNA NO ORDEM ESPECIFICA ANTES DE UMA COLUNA  (FIRST -> ANTES DE UMA DETERMINADA COLUNA) */
ALTER TABLE TABELA
ADD COLUMN COLUNA FLOAT(10,2) NOT NULL
FIRST;