/* DML - DATA MANIPULATION LANGUAGE MYSQL */


/* SELECT = PROJECAO */
SELECT * FROM TABELA 
WHERE COLUNA = 'VALOR';


/* INSERT */
INSERT INTO TABELA (COLUNA1, COLUNA2) 
     VALUES ('VALOR1', 'VALOR2');

/* UPDATE */
/* IMPORTANTE: ANTES DE REALIZAR UPDATE, FAÇA UM SELECT PARA TER CERTEZA SE É O CAMPO CERTO*/
SELECT * FROM TABELA
WHERE COLUNA = VALOR;

UPDATE TABELA
SET COLUNA = "VALOR"
WHERE COLUNA = VALOR;


/* DELETE */
/* IMPORTANTE: ANTES DE REALIZAR DELETE, FAÇA UM SELECT PARA TER CERTEZA SE É O CAMPO CERTO*/
SELECT * FROM TABELA
WHERE ID_COLUNA = VALOR;

DELETE FROM COLUNA
WHERE COLUNA = VALOR;

